### ISSUE TITLE
not running test-jwt-server

### ISSUE THREAD

**Issue by jeevan449** [leesei/test-jwt-server#1]
[root@srv jwt_fake]# test-jwt-server  -p 9090
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './keys/shared.key'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at Object.<anonymous> (/usr/lib/node_modules/test-jwt-server/secret.js:3:39)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

**Comment by leesei** [comment]
A simple file name mismatch.
Do check the latest code.
